# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@main
      with:
        name: node-build
        path: public/
      
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [windows-latest,ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@main
        with:
          name: node-build
          path: public
      - name: install
        run: npm install
      - name: Test
        run: npm test -- -u
    
